CREATE TABLE ARTICULO(
	REFERENCIA VARCHAR (10),
	AUTOR VARCHAR (30),
	FECHA DATE,
	TITULO VARCHAR (50),
	UBICACION VARCHAR (50),
	CONSTRAINT PK_REF PRIMARY KEY (REFERENCIA) 
);


CREATE TABLE SECCION(
	NUM_SECCION INT (3),
	UBICACION VARCHAR (15),
	REFERENCIA VARCHAR (10),
	CONSTRAINT PK_NUM_SECCION PRIMARY KEY (NUM_SECCION),
	CONSTRAINT FK_REF_ARTICULO FOREIGN KEY (REFERENCIA) REFERENCES ARTICULO (REFERENCIA)
);

CREATE TABLE DEPARTAMENTO(
	NUM_DPTO INT (4),
	NOMBRE VARCHAR (15),
	UBICACION VARCHAR (15),
	NUM_SECCION INT (3),
	CONSTRAINT PK_NUM_DPTO PRIMARY KEY (NUM_DPTO),
	CONSTRAINT FK_N_SECCION FOREIGN KEY (NUM_SECCION) REFERENCES SECCION (NUM_SECCION) 
);

CREATE TABLE LIBRO(
	REFERENCIA VARCHAR (10),
	ISBN varchar (10),
	GENERO VARCHAR (15),
	CONSTRAINT PK_REF_libro PRIMARY KEY (REFERENCIA) ,
	CONSTRAINT FK_REFERENCIA FOREIGN KEY (REFERENCIA) REFERENCES ARTICULO (REFERENCIA) 
);

CREATE TABLE PERIODICO(
	NUMERO INT (3),
	REFERENCIA VARCHAR (10),
	CONSTRAINT PK_REF_periodico PRIMARY KEY (REFERENCIA),
	CONSTRAINT FK_REF_1 FOREIGN KEY (REFERENCIA) REFERENCES ARTICULO (REFERENCIA)
);

CREATE TABLE REVISTA(
	NUMERO INT (3),
	REFERENCIA VARCHAR (10),
	CONSTRAINT PK_REF_revista PRIMARY KEY (REFERENCIA) ,
	CONSTRAINT FK_REF_2 FOREIGN KEY (REFERENCIA) REFERENCES ARTICULO (REFERENCIA)
);

CREATE TABLE VIDEO(
	GENERO VARCHAR (20),
	REFERENCIA VARCHAR (10),
	CONSTRAINT PK_REF_video PRIMARY KEY (REFERENCIA),
	CONSTRAINT FK_REF_3 FOREIGN KEY (REFERENCIA) REFERENCES ARTICULO (REFERENCIA)
);

CREATE TABLE DOCUMENTO(
	TEMATICA VARCHAR (15),
	REFERENCIA VARCHAR (10),
	CONSTRAINT PK_REF_doc PRIMARY KEY (REFERENCIA),
	CONSTRAINT FK_REF_4 FOREIGN KEY (REFERENCIA) REFERENCES ARTICULO (REFERENCIA)
);

CREATE TABLE SOCIO (
	DNI VARCHAR (8),
	NOMBRE VARCHAR (20),
	APELLIDO VARCHAR (20),
	DIRECCION VARCHAR (50),
	TLF INT (15),
	EMAIL VARCHAR (30),
	CONSTRAINT PK_DNI PRIMARY KEY (DNI)
);

CREATE TABLE ARTICULO_SOCIO(
	REFERENCIA VARCHAR (10),
	DNI VARCHAR (8),
	CONSTRAINT PK1_REF_SOCIO PRIMARY KEY (REFERENCIA, DNI),
	CONSTRAINT FK1_REF_ART_1 FOREIGN KEY (REFERENCIA) REFERENCES ARTICULO (REFERENCIA),
	CONSTRAINT FK2_DNI_SOCIO_1 FOREIGN KEY (DNI) REFERENCES SOCIO (DNI)
);
